# Generated by Django 4.2.4 on 2024-11-20 20:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('movies', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=32, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=64)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('phone_number', models.CharField(max_length=15, unique=True)),
                ('verification_code', models.IntegerField(blank=True, null=True)),
                ('is_phone_verified', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=False)),
                ('profile_image', models.CharField(blank=True, help_text='사용자 프로필 이미지 URL', max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='계정 생성 날짜')),
                ('bio', models.TextField(blank=True, help_text='사용자의 자기소개', null=True)),
                ('unread_notifications_count', models.PositiveIntegerField(default=0, help_text='읽지 않은 알림 수')),
                ('favorite_actors', models.ManyToManyField(blank=True, help_text='즐겨찾기한 배우 목록', related_name='favorited_actor_by_users', to='movies.actor')),
                ('favorite_directors', models.ManyToManyField(blank=True, help_text='즐겨찾기한 감독 목록', related_name='favorited_director_by_users', to='movies.director')),
                ('favorite_genres', models.ManyToManyField(blank=True, help_text='선호 장르 목록', related_name='users', to='movies.genre')),
                ('following', models.ManyToManyField(blank=True, help_text='팔로우하는 사용자 목록', related_name='followers', to=settings.AUTH_USER_MODEL)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('liked_movies', models.ManyToManyField(blank=True, help_text='좋아요한 영화 목록', related_name='liked_movies_by_users', to='movies.movie')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(help_text='알림 내용')),
                ('is_read', models.BooleanField(default=False, help_text='알림 읽음 여부')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='알림 생성 날짜')),
                ('type', models.CharField(choices=[('comment', 'Comment'), ('reply', 'Reply'), ('like', 'Like'), ('follow', 'Follow')], help_text='알림 유형', max_length=50)),
                ('link', models.CharField(blank=True, help_text='알림 클릭 시 이동할 링크', max_length=255, null=True)),
                ('user', models.ForeignKey(help_text='알림을 받을 사용자', on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
