# Generated by Django 4.2.4 on 2024-11-21 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
        ('community', '0001_initial'),
        ('accounts', '0006_alter_customuser_date_of_birth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='favorite_actors',
            field=models.ManyToManyField(blank=True, help_text='사용자가 즐겨찾기한 배우 목록', related_name='favorited_actors_by_users', to='movies.actor'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='favorite_directors',
            field=models.ManyToManyField(blank=True, help_text='사용자가 즐겨찾기한 감독 목록', related_name='favorited_directors_by_users', to='movies.director'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='favorite_genres',
            field=models.ManyToManyField(blank=True, help_text='사용자의 선호 장르 목록', related_name='favorite_genres_by_users', to='movies.genre'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='liked_movies',
            field=models.ManyToManyField(blank=True, help_text='사용자가 좋아요를 누른 영화 목록', related_name='liked_movies_by_users', to='movies.movie'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='liked_posts',
            field=models.ManyToManyField(blank=True, help_text='사용자가 좋아요를 누른 게시글 목록', related_name='liked_posts_by_users', to='community.post'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='liked_reviews',
            field=models.ManyToManyField(blank=True, help_text='사용자가 좋아요를 누른 리뷰 목록', related_name='liked_reviews_by_users', to='community.review'),
        ),
    ]
