# Generated by Django 4.2.4 on 2024-11-21 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_customuser_favorite_actors_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='profile_image',
            field=models.ImageField(blank=True, default='default_profile.png', help_text='사용자 프로필 이미지', max_length=300, null=True, upload_to='media/'),
        ),
    ]
