# Generated by Django 4.2.4 on 2024-11-20 20:35

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tmdb_id', models.IntegerField(unique=True)),
                ('name', models.CharField(max_length=255)),
                ('gender', models.CharField(choices=[('Unknown', 'Unknown'), ('Female', 'Female'), ('Male', 'Male')], default='Unknown', max_length=30)),
                ('profile_path', models.CharField(blank=True, max_length=255, null=True)),
                ('birthdate', models.DateField(blank=True, null=True)),
                ('biography', models.TextField(blank=True, null=True)),
                ('birthplace', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tmdb_id', models.IntegerField(unique=True)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tmdb_id', models.IntegerField(unique=True)),
                ('title', models.CharField(max_length=255)),
                ('overview', models.TextField(blank=True, null=True)),
                ('release_date', models.DateField(blank=True, null=True)),
                ('popularity', models.FloatField(blank=True, null=True)),
                ('poster_path', models.CharField(blank=True, max_length=255, null=True)),
                ('trailer_link', models.URLField(blank=True, max_length=500, null=True)),
                ('normalized_popularity', models.FloatField(blank=True, null=True)),
                ('genres', models.ManyToManyField(related_name='movies', to='movies.genre')),
            ],
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='뉴스 제목', max_length=255)),
                ('content', models.TextField(help_text='뉴스 내용')),
                ('url', models.URLField(help_text='뉴스 링크', max_length=500)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, help_text='저장 시간')),
                ('movie', models.ForeignKey(help_text='영화 관련 뉴스', on_delete=django.db.models.deletion.CASCADE, related_name='news', to='movies.movie')),
            ],
        ),
        migrations.CreateModel(
            name='Director',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tmdb_id', models.IntegerField(unique=True)),
                ('name', models.CharField(max_length=255)),
                ('gender', models.CharField(choices=[('Unknown', 'Unknown'), ('Female', 'Female'), ('Male', 'Male')], default='Unknown', max_length=30)),
                ('profile_path', models.CharField(blank=True, max_length=255, null=True)),
                ('birthdate', models.DateField(blank=True, null=True)),
                ('biography', models.TextField(blank=True, null=True)),
                ('birthplace', models.CharField(blank=True, max_length=255, null=True)),
                ('movies', models.ManyToManyField(related_name='director_movies', to='movies.movie')),
            ],
        ),
        migrations.CreateModel(
            name='ActorCharacter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('character_name', models.CharField(blank=True, max_length=255, null=True)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movie_roles', to='movies.actor')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actor_roles', to='movies.movie')),
            ],
        ),
        migrations.AddField(
            model_name='actor',
            name='movies',
            field=models.ManyToManyField(related_name='actor_movies', to='movies.movie'),
        ),
    ]
